apiVersion: v1
kind: Pod
metadata:
  name: hello-node
spec:
  containers:
    - image: docker.io/bennylp/hello-node:v1
      name: hello-node
      livenessProbe:
        httpGet:
          path: /healthy
          port: 5000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"
      volumeMounts:
        - mountPath: "/data"
            name: "my-data"
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
volumes:
  - name: "my-data"
    hostPath:
      path: "/var/lib/hello-node"
